
package todo_soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ToDoWebService", targetNamespace = "http://toDo_SOAP/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDoWebService {


    /**
     * 
     * @param project
     * @param priority
     * @param task
     * @param context
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addToDo", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.AddToDo")
    @ResponseWrapper(localName = "addToDoResponse", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.AddToDoResponse")
    public String addToDo(
        @WebParam(name = "task", targetNamespace = "")
        String task,
        @WebParam(name = "context", targetNamespace = "")
        String context,
        @WebParam(name = "project", targetNamespace = "")
        String project,
        @WebParam(name = "priority", targetNamespace = "")
        Integer priority);

    /**
     * 
     * @param task
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeToDo", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.RemoveToDo")
    @ResponseWrapper(localName = "removeToDoResponse", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.RemoveToDoResponse")
    public String removeToDo(
        @WebParam(name = "task", targetNamespace = "")
        String task);

    /**
     * 
     * @return
     *     returns java.lang.Byte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listToDo", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.ListToDo")
    @ResponseWrapper(localName = "listToDoResponse", targetNamespace = "http://toDo_SOAP/", className = "todo_soap.ListToDoResponse")
    public Byte listToDo();

}
